name: 'Unofficial Telefonistka GitHub Action'
description: 'Safe and Controlled GitOps Promotion Across Environments/Failure-Domains https://github.com/wayfair-incubator/telefonistka'
inputs:
  repo-token:
    description: 'The GitHub token used to manage labels'
    required: false
    default: ${{ github.token }}
# outputs:
  # time: # id of output
    # description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/commercetools/telefonistka:alpine-v1.20.0'
  entrypoint: /usr/local/bin/telefonistka
  args:
    - event
    # - ${{ inputs.who-to-greet }}
  env:
    GITHUB_OAUTH_TOKEN: ${{ inputs.repo-token }}
    APPROVER_GITHUB_OAUTH_TOKEN: ${{ inputs.repo-token }}
    TEMPLATES_PATH: "/telefonistka/templates/"
